version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: nginx
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "8090:8080"
    networks:
      - webnet
  app:
    # replace username/repo:tag with your name and image details
    image: nareshmnvs/myapp:latest
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "8099:3000"
    networks:
      - webnet
networks:
  webnet:
